### ISSUE TITLE
Open GL GetShaders Exception

### ISSUE THREAD

**Issue by karthik9313** [TASEmulators/BizHawk#3647]
### Summary
Getting exception when switching display method to Open GL. Exception details mentioned below.

### Repro
1. Open EmuHawk
2. Go to Config -> Display -> Display Method tab
3. Select Open GL
4. Restart EmuHawk
5. Get Exception

### Output
```
System.Exception: Initialization of Display Method failed; falling back to GDI+ ---> System.InvalidOperationException: Error compiling shader (GetShader)

ERROR: 0:1: '#version' : bad profile name; use es, core, or compatibility 
ERROR: 0:1: '#version' : bad tokens following profile -- expected newline 
ERROR: 0:1: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.


   at BizHawk.Bizware.OpenTK3.IGL_TK.CompileShaderSimple(Int32 sid, String source, Boolean required)
   at BizHawk.Bizware.OpenTK3.IGL_TK.CreateShader(ShaderType type, String source, String entry, Boolean required)
   at BizHawk.Bizware.OpenTK3.IGL_TK.CreateVertexShader(String source, String entry, Boolean required)
   at BizHawk.Bizware.OpenTK3.GuiRenderer..ctor(IGL owner)
   at BizHawk.Client.EmuHawk.IGLExtensions.CreateRenderer(IGL gl)
   at BizHawk.Client.EmuHawk.Program.<>c__DisplayClass2_0.<SubMain>g__CheckRenderer|2(IGL gl)
   --- End of inner exception stack trace ---
```

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.9; Win10 Enterprise 22H2; AMD R5 1400 / AMD RX 6600
- BizHawk 2.8; Win10 Enterprise 22H2; AMD R5 1400 / AMD RX 6600

![2023-04-26_01-11](https://user-images.githubusercontent.com/23000378/234475321-20d628ef-2980-445c-9e67-665ed018d424.png)

**Comment by YoshiRulz** [comment]
Duplicate of #3456. This is a driver issue. Make sure `EmuHawk.exe` is set to use your discrete GPU, and if it's still failing, update your drivers.

**Comment by karthik9313** [comment]
Thanks for the update, however I have the latest AMD drivers version 23.4.2 dated 12-Apr-2023. And I don't have any iGPU, only RX 6600.

**Comment by karthik9313** [comment]
This is resolved in the latest dev build, thanks a lot!! 👍
