### ISSUE TITLE
System.Exception: Initialization of Display Method failed

### ISSUE THREAD

**Issue by Bluskix** [TASEmulators/BizHawk#3831]
I got this error when i try too open the game with OpenGL(hoping for more FPS),i have alredy installed *prereqs*.

```
System.Exception: Initialization of Display Method failed; falling back to GDI+ ---> System.InvalidOperationException: Error compiling shader (GetShader)

ERROR: 0:1: '#version' : bad profile name; use es, core, or compatibility 
ERROR: 0:1: '#version' : bad tokens following profile -- expected newline 
ERROR: 0:1: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.

   in BizHawk.Bizware.OpenTK3.IGL_TK.CompileShaderSimple(Int32 sid, String source, Boolean required)
   in BizHawk.Bizware.OpenTK3.IGL_TK.CreateShader(ShaderType type, String source, String entry, Boolean required)
   in BizHawk.Bizware.OpenTK3.IGL_TK.CreateVertexShader(String source, String entry, Boolean required)
   in BizHawk.Bizware.OpenTK3.GuiRenderer..ctor(IGL owner)
   in BizHawk.Client.EmuHawk.IGLExtensions.CreateRenderer(IGL gl)
   in BizHawk.Client.EmuHawk.Program.<>c__DisplayClass2_0.<SubMain>g__CheckRenderer|2(IGL gl)
```

**Comment by CasualPokePlayer** [comment]
Please try the latest dev build.

**Comment by Bluskix** [comment]
> Please try the latest dev build.

2.9.1 right? same error

**Comment by Bluskix** [comment]
> Not the latest release, a [development build](https://github.com/TASEmulators/BizHawk#development-builds). There have been a lot of changes to the OpenGL renderer since 2.9.1.

ty,now is working
