### ISSUE TITLE
OpenGL shader compile fails

### ISSUE THREAD

**Issue by raspberryky** [TASEmulators/BizHawk#3456]
BizHawk (2.8.0) gets the following error when opening after changing the display method to OpenGL on Mupen64Plus.

"System.Exception: Initialization of Display Method failed; falling back to GDI+ ---> System.InvalidOperationException: Error compiling shader (GetShader)

ERROR: 0:2: '#version' : bad profile name; use es, core, or compatibility 
ERROR: 0:2: '#version' : bad tokens following profile -- expected newline 
ERROR: 0:2: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.

   at BizHawk.Bizware.OpenTK3.IGL_TK.CompileShaderSimple(Int32 sid, String source, Boolean required)
   at BizHawk.Bizware.OpenTK3.IGL_TK.CreateShader(ShaderType type, String source, String entry, Boolean required)
   at BizHawk.Bizware.OpenTK3.IGL_TK.CreateVertexShader(String source, String entry, Boolean required)
   at BizHawk.Bizware.OpenTK3.GuiRenderer..ctor(IGL owner)
   at BizHawk.Client.EmuHawk.IGLExtensions.CreateRenderer(IGL gl)
   at BizHawk.Client.EmuHawk.Program.<>c__DisplayClass2_0.<SubMain>g__CheckRenderer|2(IGL gl)
   --- End of inner exception stack trace ---"

OS: Windows 10 Home Edition
CPU: Intel i7-4790K, 4 GHz
GPU: Radeon RX 6600
Memory: 16 GB 1800 MHz RAM

I know the specs on my computer are a little strange, but I'm assuming the issue is either with the software or with its compatibility with my PC and not with the hardware itself. I'm trying to run an N64 ROM and the other two shader compilers don't render it correctly (certain textures are black, some items have the wrong color, etc.).

**Comment by YoshiRulz** [comment]
Does this only happen after loading an N64 rom?

**Comment by CasualPokePlayer** [comment]
Is your thing trying to use OpenGL ES? That's probably not going to be compatible.

**Comment by raspberryky** [comment]
YoshiRulz: I didn't try changing to OpenGL until after I tried running the ROM. The error still occurred after restarting the software and only changing the display method.

CasualPokePlayer: I am not sure if I am using OpenGL ES. I simply have what I got off the base install, if that makes any sense. I selected OpenGL from the screen shown in the following screenshot:
![image](https://user-images.githubusercontent.com/92833259/202839001-0a9beb68-dde6-4bf5-a508-a29a4a464637.png)

**Comment by CasualPokePlayer** [comment]
Whether you are using OpenGL proper or OpenGL ES would be dependent on your device and drivers. Googling around I think your device should support OpenGL proper, so this can probably be blamed on bad drivers.

**Comment by raspberryky** [comment]
That makes sense. I'll do some digging in control panel and see if I can't resolve the driver issue on my own then. I'll try to leave an update here if I either resolve it or hit another bump. I recently had to do a full reinstall of Windows, so a driver issue doesn't sound too out of the ordinary.

**Comment by CasualPokePlayer** [comment]
Another odd thing however is you're saying the N64 core loaded ROMs anyways but had fucked up rendering? mupen inits opengl by itself (it's not reliant on the display method here, even if you have direct3d9 or gdi+ set mupen still ends up using opengl stuff). The issues you describe seem similar to bad Intel iGPU drivers? Does your PC only have that Radeon card or does it also pack an iGPU it might be falling back on?

**Comment by raspberryky** [comment]
I do have integrated graphics on the motherboard, not sure if the driver for that is still active though. Should I try to both update my Radeon card's driver and disable my IG driver then? Unless I'm misunderstanding what you mean by iGPU.

**Comment by CasualPokePlayer** [comment]
I would guess you iGPU is being used and is having these issues.

**Comment by raspberryky** [comment]
I hope so. This seems more and more like I'm having device issues again with Windows, so this may have uncovered another issue entirely with my PC. I'll let you know if the driver update fixes it.
I suppose there might also be an issue with my global settings for the Radeon Adrenaline (equivalent to NVidia Control Panel), or another piece of software unrelated to BizHawk.

**Comment by raspberryky** [comment]
Same issue after updating graphics drivers. I'm going to check and see if there's any other issues with my current build that could be making this happen.

**Comment by raspberryky** [comment]
I've changed and reset everything I can think to modify, and I'm still getting the same result. The OpenGL issue still occurs on startup if I try to change it manually, but at the very least Mupen seems to work fine with other ROMs. This still might be something to look into, but for the time being I'd be fine with closing this thread.

**Comment by Spikestuff** [comment]
> This still might be something to look into,

[It's basically this but Radeon](https://github.com/TASEmulators/BizHawk/issues/2192#issuecomment-653536555).

**Comment by YoshiRulz** [comment]
Another user reported the same error on Discord using 2.6, and it stopped appearing after switching to 2.8.

**Comment by CasualPokePlayer** [comment]
Googling the error further, I don't think it would be caused by OpenGL ES being used. I think this is just a straight driver bug. The profile is specified to be optional, and even then, since use version 110, it is not allowed to be used in the first placed (the minimum it may be used is 150). If we were to try to comply with this bs driver, it would probably break on other actually compliant drivers.

GLSL spec for reference:
```
A profile argument can only be used with version 150 or greater. If no profile argument is provided and
the version is 150 or greater, the default is core. If version 300 or 310 is specified, the profile argument is
not optional and must be es, or a compile-time error results.
```

**Comment by CasualPokePlayer** [comment]
Actually, taking a look at the shader, it does seem that we put in a space, then a comment on the OpenGL version. Perhaps then it's the space being an issue and the driver assuming we're specifying a profile (although that wouldn't be allowed anyways), and then not liking how there is nothing after the space (other than the comment, which it seems to ignore as it should). Perhaps then moving the comment to a line above or below and/or removing the space would fix it.
